source 'https://api.berkshelf.com'

cookbook 'ruby-install'
cookbook 'nginx'
cookbook 'puma'
cookbook 'sudo'
cookbook 'ssh-keys'
cookbook 'postgresql'
cookbook 'apt'
cookbook 'photo-album', path: 'site-cookbooks/photo-album/'
