source 'https://api.berkshelf.com'

cookbook 'ruby-install'
cookbook 'nginx'
cookbook 'puma'
cookbook 'sudo'
cookbook 'ssh-keys'
cookbook 'postgresql'
cookbook 'apt'
cookbook 'database'
cookbook 'redisio'
cookbook 'photo-album', path: 'site-cookbooks/photo-album/'
cookbook 'backup', '1.3.0'
cookbook 'chef-vault'
